# Question 1:
__Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays__

In [8]:
import numpy as npy

a1 = npy.array([2,0,8,6,9,5])
a2 = npy.array([5,7,9,3,4,6])
print("Original Array:")
print(a1)
print(a2)
print('1. Greater comparison of array:\n')
print(npy.greater(a1,a2))
print('\n2. Greater_equal comparison of array:\n')
print(npy.greater_equal(a1,a2))
print('\n3. Less comparison of array:\n')
print(npy.less(a1,a2))
print('\n4. Less_equal comparison of array:\n')
print(npy.less_equal(a1,a2))

Original Array:
[2 0 8 6 9 5]
[5 7 9 3 4 6]
1. Greater comparison of array:

[False False False  True  True False]

2. Greater_equal comparison of array:

[False False False  True  True False]

3. Less comparison of array:

[ True  True  True False False  True]

4. Less_equal comparison of array:

[ True  True  True False False  True]


# Question 2:
__Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives__

In [12]:
print('1. Array of 10 zeroes as follows:\n')
x = npy.zeros(10)
print(x)
print('\n2. Array of 10 ones as follows:\n')
x = npy.ones(10)
print(x)
print('\n3. Array of 10 fives as follows:\n')
x = npy.ones(10)*5
print(x)

1. Array of 10 zeroes as follows:

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

2. Array of 10 ones as follows:

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

3. Array of 10 fives as follows:

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Question 3:
__Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array__

In [18]:
a = npy.array([[2,0,8,6,9,5],[5,7,9,3,4,6]])
print('Original Array:\n',a)
print('\nSum of all elements are as follows:\n')
print(npy.sum(a))
print('\nSum of all each column are as follows:\n')
print(npy.sum(a,axis=0))
print('\nSum of all each row are as follows:\n')
print(npy.sum(a,axis=1))

Original Array:
 [[2 0 8 6 9 5]
 [5 7 9 3 4 6]]

Sum of all elements are as follows:

64

Sum of all each column are as follows:

[ 7  7 17  9 13 11]

Sum of all each row are as follows:

[30 34]


# Question 4:
__Write a NumPy program to add, subtract, multiply, divide arguments element-wise.__

In [32]:
a1 = npy.array([[2,6,4],[3,7,5],[6,9,6]])
a2 = npy.array([[7,5,2],[1,2,4],[7,6,4]])
print('First array:\n')
print(a1)
print('\nSecond array:\n')
print(a2)
print('\nAddition:\n')
print(npy.add(a1,a2))
print('\nSubtraction:\n')
print(npy.subtract(a1,a2))
print('\nMultiplication:\n')
print(npy.multiply(a1,a2))
print('\nDivide:\n')
print(npy.divide(a1,a2))

First array:

[[2 6 4]
 [3 7 5]
 [6 9 6]]

Second array:

[[7 5 2]
 [1 2 4]
 [7 6 4]]

Addition:

[[ 9 11  6]
 [ 4  9  9]
 [13 15 10]]

Subtraction:

[[-5  1  2]
 [ 2  5  1]
 [-1  3  2]]

Multiplication:

[[14 30  8]
 [ 3 14 20]
 [42 54 24]]

Divide:

[[0.28571429 1.2        2.        ]
 [3.         3.5        1.25      ]
 [0.85714286 1.5        1.5       ]]


# Question 5:
__Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.__

In [34]:
a1 = npy.array([[2,6,4,6,9,6]])
print('Trigonometric sine:')
print(npy.sin(a1)*npy.pi/180)
print('\nTrigonometric cosine:')
print(npy.cos(a1)*npy.pi/180)
print('\nTrigonometric cosine:')
print(npy.tan(a1)*npy.pi/180)

Trigonometric sine:
[[ 0.01587023 -0.00487672 -0.0132087  -0.00487672  0.00719282 -0.00487672]]

Trigonometric cosine:
[[-0.00726313  0.01675813 -0.01140823  0.01675813 -0.01590222  0.01675813]]


# Question 6:
__Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels__

In [3]:
import pandas as pd
import numpy as npy

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, npy.nan, 9, 20, 14.5, npy.nan, 8, 19],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)



        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes


# Question 7:
__Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.__

In [6]:
print('Columns are as follows:')

df[['name','score']]

Columns are as follows:


name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

# Question 8:
__Write a Pandas program to join the two given dataframes along rows and assign all data.__

In [16]:
stud_data = {'st_id':[1,2,3,4,5],'st_nm':['sagar','madhav','raju','reva','pooja'],'marks':[23,45,76,43,65]}
labels = {'a','b','c','d','e'}
res = pd.DataFrame(stud_data , index=labels)
print('First DataFrame:\n')
res


First DataFrame:



st_id   st_nm  marks
e      1   sagar     23
b      2  madhav     45
d      3    raju     76
c      4    reva     43
a      5   pooja     65

In [17]:
stud_data2 = {'st_id':[9,8,7,6],'st_nm':['sameer','maddy','ruhi','revati'],'marks':[43,65,98,56]}
label2 = {'a','b','c','d'}
res2 = pd.DataFrame(stud_data2 , index=label2)
print('Second DataFrame:\n')
res2

Second DataFrame:



st_id   st_nm  marks
d      9  sameer     43
b      8   maddy     65
c      7    ruhi     98
a      6  revati     56

In [19]:
print('Joinning Two dataframe by row with all data:\n')
result = pd.concat([res,res2])
result

Joinning Two dataframe by row with all data:



st_id   st_nm  marks
e      1   sagar     23
b      2  madhav     45
d      3    raju     76
c      4    reva     43
a      5   pooja     65
d      9  sameer     43
b      8   maddy     65
c      7    ruhi     98
a      6  revati     56

# Question 9:
__Write a Pandas program to detect missing values of a given DataFrame. Display True or False.__

In [24]:
stud_data = {'st_id':[1,2,3,4,5,9,8],'st_nm':['sagar','madhav','raju',npy.nan,'reva','pooja',npy.nan],
             'marks':[23,npy.nan,45,npy.nan,76,43,65]}
label = {'a','b','c','d','e','f','g'}
res = pd.DataFrame(stud_data,index=label)
print('Original DataFrame:')
print(res)
print('\nMissing Value Display True or False:')
print(res.isna())

Original DataFrame:
   st_id   st_nm  marks
e      1   sagar   23.0
b      2  madhav    NaN
d      3    raju   45.0
c      4     NaN    NaN
f      5    reva   76.0
a      9   pooja   43.0
g      8     NaN   65.0

Missing Value Display True or False:
   st_id  st_nm  marks
e  False  False  False
b  False  False   True
d  False  False  False
c  False   True   True
f  False  False  False
a  False  False  False
g  False   True  False


# Question 10:
__Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.__

In [31]:
res1 = pd.Series(['sharvari','Rajeshwari','Sourabhi','Lavina'])
# res = pd.Series([1,2,3,45,5,6])
# res
res1

0      sharvari
1    Rajeshwari
2      Sourabhi
3        Lavina
dtype: object